src/components/PhaseBanner.tsx, src/components/ResidentLayout.tsx, src/styles/PhaseBanner.module.scss
- add new phase banner component to replace the out of date one that comes packaged with the react library
=> fix phase banner

cypress/fixtures/document-submission-response-singular.json, cypress/fixtures/document-submission-response.json, cypress/fixtures/evidence-request-response-singular.json, cypress/integration/authentication.ts, cypress/integration/upload-a-document.spec.ts, package-lock.json, package.json, src/boundary/response-mapper.test.ts, src/boundary/response-mapper.ts, src/components/UploaderForm.test.tsx, src/components/UploaderForm.tsx, src/domain/document-submission.ts, src/gateways/__mocks__/s3-gateway.ts, src/gateways/s3-gateway.test.ts, src/gateways/s3-gateway.ts, src/pages/resident/[requestId]/upload.tsx, src/services/upload-form-model.test.ts, src/services/upload-form-model.ts
- S3 Gateway to post files
- Update submission response to include document type
- Refactor uploadform to use document submissions
- Implement form model class and file upload from form
=> DES-42 S3 Gateway and Form Model

cypress/integration/create-evidence-request.spec.ts, jest.config.js, package-lock.json, src/components/ConfirmRequestDialog.test.tsx, src/components/ConfirmRequestDialog.tsx, src/components/DashboardLayout.tsx, src/components/NewRequestForm.test.tsx, src/components/NewRequestForm.tsx, src/components/ResidentLayout.tsx, src/gateways/s3-gateway.test.ts, src/gateways/s3-gateway.ts, src/styles/Panel.module.scss, test/setup.js
- Homepage is 404
- Show confirmation dialog before sending a request
- Fix order of formdata when POSTing to S3
=> DES-51 Confirm evidence request dialog

.circleci/config.yml
=> Enable Production deploy

serverless.yml
=> Add back in the token for POST evidence_requests

cypress/fixtures/document-submission-response-singular.json, cypress/integration/accept-reject-evidence.spec.ts, cypress/integration/upload-a-document.spec.ts, package-lock.json, package.json, src/components/AcceptDialog.tsx, src/components/UploaderForm.test.tsx, src/components/UploaderForm.tsx, src/domain/document-submission.ts, src/gateways/internal-api.test.ts, src/gateways/internal-api.ts, src/pages/dashboard/resident/[residentId]/document/[documentId].tsx, src/pages/resident/[requestId]/upload.tsx, src/services/upload-form-model.test.ts, src/services/upload-form-model.ts
- Update Cypress
- Convert document submission PATCH to top level
- Implement HTTP request to approve a document
=> DES-66 Approve document API call

src/components/EvidenceRequestTable.tsx, src/components/ResidentTable.tsx
We need a way to get to the resident page from the resident
=> Add Review link to residents table

cypress/integration/upload-a-document.spec.ts, src/services/upload-form-model.test.ts, src/services/upload-form-model.ts
Reverts LBHackney-IT/document-evidence-store-frontend#36
=> Revert "Temporarily disable patch to document submissions"

package-lock.json, serverless.yml, services.json, src/components/ServicesLayout.tsx, src/domain/service-area.ts, src/domain/service.ts, src/pages/services/index.tsx, src/services/request-authorizer.ts, src/services/service-area-helper.test.ts, src/services/service-area-helper.ts
https://hackney.atlassian.net/browse/DES-140
- Created page `/services`
- Services are shown if the user is a member of the service area google group
- Added services.json with dummy values (will need to be updated with real values later on)
=> DES-140: created choose a service screen

cypress/fixtures/document_submissions/get-many.json, cypress/fixtures/residents/getResident.json, cypress/integration/view-and-manage-evidence.spec.ts, src/components/EvidenceTile.test.tsx, src/components/EvidenceTile.tsx, src/gateways/evidence-api.test.ts, src/gateways/evidence-api.ts, src/pages/dashboard/residents/[residentId]/index.tsx, test/mocks/behaviours.json, test/mocks/fixtures/document-submissions.js, test/mocks/fixtures/residents-requests.js
- Updated the page to show all the document submissions of a resident
- Added gateway functions to fetch the document submissions and the resident from the evidence-api
- Added tests
=> Show document submissions for a resident

cypress/integration/search-for-resident.spec.ts, cypress/integration/view-and-manage-evidence.spec.ts, src/components/EvidenceRequestTable.tsx, src/pages/resident/[requestId]/confirmation.tsx, src/pages/teams/[teamId]/dashboard/index.tsx, src/pages/teams/[teamId]/dashboard/residents/[residentId]/index.tsx
Comment non-implemented UI to see only the features that are built in the backend.
=> Comment non-implemented UI

serverless.yml
https://hackney.atlassian.net/browse/DES-172
=> DES-172: increase lambda timeout to 30 seconds

src/pages/teams/[teamId]/dashboard/residents/[residentId]/document/[documentSubmissionId].tsx
Fix file extension from 'jpg' to 'jpeg'
=> Fix file extension

src/pages/teams/[teamId]/dashboard/residents/[residentId]/document/[documentSubmissionId].tsx, test/mocks/fixtures/generate-download-url.js
- Fix displaying preview for pdf and images
=> Fix displaying preview

src/components/UploaderPanel.test.tsx, src/components/UploaderPanel.tsx
https://hackney.atlassian.net/browse/DES-174
=> DES-174: upload panel accepts multiple documents

cypress/fixtures/evidence_requests/id.json, cypress/fixtures/evidence_requests/index.json, cypress/integration/upload-a-document.spec.ts, src/components/NewRequestForm.test.tsx, src/domain/team.ts, src/pages/resident/[requestId]/confirmation.tsx, src/services/team-helper.test.ts, src/services/team-helper.ts, teams.json
- Shows a SLA message on the submission confirmation page based on the team the document was submitted for.
=> Show SLA message on submission confirmation page

cypress/integration/view-and-manage-evidence.spec.ts, src/components/ResidentTable.tsx
- Removed the "Review" button on dashboard page and moved the link to the resident name to follow the new designs
=> Remove review button and move link to resident name

cypress/integration/view-and-manage-evidence.spec.ts, src/pages/teams/[teamId]/dashboard/residents/[residentId]/document/[documentSubmissionId].tsx
- Changed the "Download" button to "Open in new tab" to better reflect its functionality
=> Open document in a new tab

src/pages/teams/[teamId]/dashboard/residents/[residentId]/document/[documentSubmissionId].tsx
https://hackney.atlassian.net/browse/DES-191
=> DES-191: Display updated document type on the document page

cypress/fixtures/evidence_requests/id.json, cypress/fixtures/evidence_requests/index.json, cypress/integration/upload-a-document.spec.ts, src/boundary/response-mapper.test.ts, src/domain/evidence-request.ts, src/pages/resident/[requestId]/confirmation.tsx
https://hackney.atlassian.net/browse/DES-128
=> DES-128: display residentReferenceId to the resident

next.config.js
https://hackney.atlassian.net/browse/DES-197
=> DES-197: redirect from `/` to `/teams`

teams.json
https://hackney.atlassian.net/browse/DES-219
=> DES-219: add Security_Team group

teams.json
https://hackney.atlassian.net/browse/DES-219
=> DES-219: add Security_Testing group

auth-groups.json
https://hackney.atlassian.net/browse/DES-219
=> DES-219: add Security_Testing group to authorized groups

src/pages/teams/[teamId]/dashboard/residents/[residentId]/document/[documentSubmissionId].tsx
Added a button on the document details page to allow the user to copy the page's URL to clipboard
=> Add copy to clipboard button

src/pages/teams/[teamId]/dashboard/residents/[residentId]/document/[documentSubmissionId].tsx
Changed the way the link of the page was being accessed in the function that copies it to the clipboard
=> Des 50 copy to clipboard

cypress/integration/upload-a-document.spec.ts, src/components/NewRequestForm.test.tsx, src/domain/team.ts, src/pages/resident/[requestId]/confirmation.tsx, src/pages/resident/[requestId]/index.tsx, src/services/team-helper.test.ts, src/styles/InterruptionCard.module.scss, teams.json
https://hackney.atlassian.net/browse/DES-187
- Removed green box and image from resident landing page
=> DES-187: Show bespoke message per service on resident landing page

src/pages/resident/[requestId]/index.tsx
https://hackney.atlassian.net/browse/DES-187
=> DES-187: pass correct reference ID to continue button

serverless.yml
https://hackney.atlassian.net/browse/DES-139
=> DES-139: typo in serverless config

src/components/PhaseBanner.tsx, src/pages/resident/[requestId]/confirmation.tsx
https://hackney.atlassian.net/browse/DES-139
=> DES-139: use backticks to correctly set values

src/components/DashboardLayout.tsx, src/pages/teams/index.tsx, teams.json
DES-198
DES-208 - subtask:
- Redirect user to dashboard when they are in only one team
DES-209 - subtask:
- Remove the "Switch team" button when user is in only one team
=> Redirect from /teams to dashboard when user is in only one team

src/components/DashboardLayout.tsx, src/components/ResidentLayout.tsx, src/pages/404.tsx, src/pages/access-denied.tsx, src/pages/login.tsx, src/pages/resident/[requestId]/confirmation.tsx, src/pages/resident/[requestId]/index.tsx, src/pages/resident/[requestId]/upload.tsx
https://hackney.atlassian.net/browse/DES-139
=> DES-139: fix issues with env property being undefined

src/components/DashboardLayout.tsx
https://hackney.atlassian.net/browse/DES-139
=> DES-139: fix DashboardLayout after merge to main

src/components/AcceptDialog.tsx, src/components/RejectDialog.tsx
- updated AcceptDialog to not trigger the validation when it shouldn't
- updated the AcceptDialog so that validation is triggered on submitting the form
=> FIx AcceptDialog

serverless.yml
=> DES-252: updating staging SSL certificate ARN

src/pages/login.tsx
=> DES-252: temporary logging to help with debugging

serverless.yml
=> DES-252: set frontend_traffic-stg security group

.circleci/config.yml, serverless.yml
- Uncomment production config
- Updated security group, subnets and certificate
=> Uncomment production config and update sg, subnets and certificate

serverless.yml
=> DES-252: remove redundant API Gateway path

serverless.yml
=> DES-252: enable xray to help with debugging

auth-groups.json
https://hackney.atlassian.net/browse/DES-267
=> DES-267: add elections-team and repairs-contact-centre-team to auth groups

.circleci/config.yml, serverless.yml, src/gateways/documents-api.ts, src/gateways/evidence-api.ts, src/gateways/internal-api.ts
- This will only work in Staging, because we haven't created the Prod lambda layer
- If this works then we need to make the same Axios changes to 
- documents-api.ts
-  internal-api.ts
=> DES-253: retrieve palo altos SSL certificate from lambda layer

serverless.yml, src/gateways/evidence-api.ts
=> DES-253: print NODE_ENV; move layers around

src/gateways/evidence-api.ts
=> DES-253: revert triple equals check

teams.json
Add Repairs Contact Centre and Electoral Services teams
=> Add Repairs Contact Centre and Electoral Services teams

serverless.yml, src/gateways/evidence-api.ts
=> DES-253: remove custom SSL certificate

src/pages/teams/[teamId]/dashboard/residents/[residentId]/index.tsx
https://hackney.atlassian.net/browse/DES-302
=> Hide document submission containing no document file extension

auth-groups.json
https://hackney.atlassian.net/browse/DES-280
=> DES-280: updated team name to be inline with EvidenceAPI PR 74

cypress/fixtures/evidence_requests/id.json, cypress/fixtures/evidence_requests/index.json, src/boundary/response-mapper.test.ts, src/components/ConfirmRequestDialog.test.tsx, src/components/NewRequestForm.test.tsx, src/components/NewRequestForm.tsx, src/domain/evidence-request.ts, src/gateways/evidence-api.test.ts, src/gateways/evidence-api.ts, src/gateways/internal-api.test.ts, src/gateways/internal-api.ts, src/pages/resident/[requestId]/confirmation.tsx, src/pages/resident/[requestId]/index.tsx, src/pages/teams/[teamId]/dashboard/index.tsx, test/mocks/fixtures/document-submissions.js
https://hackney.atlassian.net/jira/software/projects/DES/boards/45?selectedIssue=DES-243
- Changed variable name from `serviceRequestedBy` to `team`
=> Change serviceRequestedBy to team

src/gateways/documents-api.ts
https://hackney.atlassian.net/browse/DES-308
=> DES-308: use token directionary lookup

README.md, next.config.js, package.json
https://hackney.atlassian.net/browse/DES-250
Create new npm script to run the mock server
=> DES-250: Enable Web Browser XSS Protection

auth-groups.json
=> Grant prod access to other service areas

src/components/NewRequestForm.tsx, src/gateways/internal-api.ts
https://hackney.atlassian.net/jira/software/projects/DES/boards/45?selectedIssue=DES-221
=> Show the error message received from evidence-api on the request form

src/gateways/evidence-api.test.ts, src/gateways/evidence-api.ts
https://hackney.atlassian.net/browse/DES-309
=> DES-309: filter headers before sending them to EvidenceAPI

serverless.yml
See https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings.html
=> DES-309: configure API Gateway to accept binary media types

cypress/fixtures/document_submissions/get-many.json, cypress/fixtures/document_submissions/get-rejected.json, cypress/integration/view-and-manage-evidence.spec.ts, package-lock.json, package.json, src/boundary/response-mapper.ts, src/components/History.tsx, src/domain/document-submission.ts, src/gateways/evidence-api.test.ts, src/gateways/evidence-api.ts, src/gateways/internal-api.test.ts, src/gateways/internal-api.ts, src/pages/teams/[teamId]/dashboard/residents/[residentId]/document/[documentSubmissionId].tsx, src/pages/teams/[teamId]/dashboard/residents/[residentId]/index.tsx, src/styles/globals.scss, test/mocks/behaviours.json, test/mocks/fixtures/document-submissions.js, test/mocks/fixtures/get-document.js, types/api.d.ts
- Display rejected documents
- Display rejection reason on documents page
- Provide email address to EvidenceAPI
=> DES-281: display rejected documents

cypress/fixtures/evidence_requests/index.json, cypress/integration/view-evidence-requests.spec.ts, src/components/EvidenceRequestTable.tsx, src/components/ResidentTable.tsx, src/domain/evidence-request.ts, types/api.d.ts
- Add `userRequestedBy` to the evidence request
- Show `userRequestedBy` on the "Requests" and "Residents" pages
- Add cypress test
=> Add user requested by to the evidence request and show it in the UI

auth-groups.json, teams.json
Added configuration for Housing Register team
Jira card: https://hackney.atlassian.net/browse/DES-337
=> Add configuration for Housing Register team

cypress/fixtures/document_submissions/create.json, cypress/fixtures/document_submissions/get-approved.json, cypress/fixtures/document_submissions/get-expired.json, cypress/fixtures/document_submissions/get-many.json, cypress/fixtures/document_submissions/get-pdf.json, cypress/fixtures/document_submissions/get-png.json, cypress/fixtures/document_submissions/get-rejected.json, cypress/fixtures/document_submissions/index.json, cypress/integration/view-and-manage-evidence.spec.ts, src/boundary/response-mapper.test.ts, src/boundary/response-mapper.ts, src/components/History.tsx, src/domain/document-submission.ts, src/helpers/formatters.ts, types/api.d.ts
Added retention to document submission and displayed it on the document submission page
Jira card: https://hackney.atlassian.net/browse/DES-325
=> Add retention to document submission

src/pages/404.tsx, src/pages/login.tsx, src/pages/resident/[requestId]/confirmation.tsx, src/pages/resident/[requestId]/index.tsx, src/pages/resident/[requestId]/upload.tsx, src/pages/teams/[teamId]/dashboard/index.tsx, src/pages/teams/[teamId]/dashboard/requests/index.tsx, src/pages/teams/[teamId]/dashboard/requests/new.tsx, src/pages/teams/[teamId]/dashboard/residents/[residentId]/document/[documentSubmissionId].tsx, src/pages/teams/[teamId]/dashboard/residents/[residentId]/index.tsx, src/pages/teams/index.tsx
https://hackney.atlassian.net/browse/DES-339
=> DES-339: Update page title tags

src/pages/_document.tsx
https://hackney.atlassian.net/browse/DES-342
=> DES-342: Update language identifier to UK English

src/pages/teams/[teamId]/dashboard/residents/[residentId]/document/[documentSubmissionId].tsx
https://hackney.atlassian.net/browse/DES-340
=> DES-340: Update alternative text for uploaded document

src/components/NewRequestForm.tsx
https://hackney.atlassian.net/browse/DES-344
=> DES-344: Validate phone number on new request form

src/gateways/internal-api.ts, src/pages/teams/[teamId]/dashboard/requests/new.tsx
https://hackney.atlassian.net/browse/DES-323
=> DES-323: Provide NotificationEmail to EvidenceAPI

cypress/fixtures/document_submissions/get-approved.json, cypress/integration/view-and-manage-evidence.spec.ts, src/boundary/response-mapper.ts, src/components/History.tsx, src/domain/document-submission.ts, src/pages/teams/[teamId]/dashboard/residents/[residentId]/document/[documentSubmissionId].tsx, types/api.d.ts
https://hackney.atlassian.net/jira/software/projects/DES/boards/45?selectedIssue=DES-350
Display uploaded and accepted events in the History component.
=> Display uploaded and accepted events in the History component

auth-groups.json, cypress/integration/upload-a-document.spec.ts, teams.json
Jira card: https://hackney.atlassian.net/browse/DOC-261
Added configuration for the demo team
=> Add configuration for the demo team

src/pages/teams/[teamId]/dashboard/requests/index.tsx
https://hackney.atlassian.net/browse/DOC-296
- Moved "New request" button to the top of the page
=> Move Make a new request button to the top of the page

cypress/integration/create-evidence-request.spec.ts, package-lock.json, src/components/ConfirmRequestDialog.test.tsx, src/components/ConfirmRequestDialog.tsx
Link to Jira card: https://hackney.atlassian.net/browse/DOC-298
Update new request confirmation dialog based on new designs
=> Update new request confirmation dialog based on new designs

src/gateways/internal-api.test.ts, src/gateways/internal-api.ts
Link to Jira card: https://hackney.atlassian.net/browse/DOC-387
=> Increase the request payload size

.env.sample, serverless.yml, src/components/DashboardLayout.tsx
Link to Jira card: https://hackney.atlassian.net/browse/DOC-413
Updated the staff facing UI to contain a link to the feedback form
=> Add feedback form link to staff facing UI

.env.sample, serverless.yml, src/components/DashboardLayout.tsx, src/components/PhaseBanner.tsx, src/pages/teams/[teamId]/dashboard/index.tsx, src/pages/teams/[teamId]/dashboard/requests/index.tsx, src/pages/teams/[teamId]/dashboard/requests/new/[step].tsx, src/pages/teams/[teamId]/dashboard/residents/[residentId]/document/[documentSubmissionId].tsx, src/pages/teams/[teamId]/dashboard/residents/[residentId]/index.tsx
Link to Jira card: https://hackney.atlassian.net/browse/DOC-413
=> Fix staff feedback form link

.env.sample, serverless.yml, src/pages/teams/[teamId]/dashboard/index.tsx, src/pages/teams/[teamId]/dashboard/requests/index.tsx, src/pages/teams/[teamId]/dashboard/requests/new/[step].tsx, src/pages/teams/[teamId]/dashboard/residents/[residentId]/document/[documentSubmissionId].tsx, src/pages/teams/[teamId]/dashboard/residents/[residentId]/index.tsx
Link to Jira card: https://hackney.atlassian.net/browse/DOC-413
=> Fix staff feedback form

package-lock.json, package.json, serverless.yml, src/ga/gtag.ts, src/pages/_app.test.tsx, src/pages/_app.tsx, src/pages/_document.tsx
=> Add ga to the website

auth-groups.json, teams.json
https://hackney.atlassian.net/browse/DOC-685
Adding config for Admission and Pupil Benefits (School's Admissions).
- Added Google Group
- Added reasons, landing message and SLA.
=> Add Admission and Pupil Benefits config as part of onboarding

src/boundary/response-mapper.ts, src/gateways/internal-api.test.ts
Taking in changes from Andy's comments on previous PR here:
https://github.com/LBHackney-IT/document-evidence-store-frontend/pull/219
=> Refactor mapping and remove unused method

auth-groups.json
https://hackney.atlassian.net/browse/DOC-844
Give school admissions team access to production.
=> Give school admissions access to production

cypress/integration/upload-a-document.spec.ts, src/pages/resident/[requestId]/upload.tsx
Link to Jira card: https://hackney.atlassian.net/browse/DOC-841
- Added guidance on how to select multiple files for upload
- Updated cypress tests to check for the new text
=> Add guidance on how to select multiple files for upload

cypress/integration/upload-a-document.spec.ts, src/components/UploaderPanel.test.tsx, src/components/UploaderPanel.tsx
Link to Jira card: https://hackney.atlassian.net/browse/DOC-854
- Added a button that allows the resident to remove the selected files for upload to avoid uploading unwanted files
- Added cypress test
=> Add button to remove selected files for upload

src/components/UploaderForm.test.tsx, src/components/UploaderForm.tsx, src/services/upload-form-model.ts
Link to Jira card: https://hackney.atlassian.net/browse/DOC-855
Commented out validation for the upload page to allow partial uploads and disabled the button when there's no file attached to prevent empty submissions. This is also a quick fix for a bug which allowed empty submissions before.
https://hackney.atlassian.net/browse/DOC-964 was created in Jira to implement proper validation on the form instead of having the submit button disabled.
=> Allow partial uploads

src/services/upload-form-model.ts
Link to Jira card: https://hackney.atlassian.net/browse/DOC-855
This is a bug fix to avoid iterating over an empty array of files.
=> Fix iterating over empty files array bug

auth-groups.json
Adding Housing Management (MMH) to production so they can use DES in prod.
=> Add Housing Management to production

cypress/fixtures/document_submissions/get-many.json, package-lock.json, src/boundary/response-mapper.ts, types/api.d.ts
Updated the api definition for `DocumentSubmissionResponse` to fix a failing test in staging
=> Update api definition for DocumentSubmissionResponse to fix failing test

src/components/ImagePreview.tsx
https://hackney.atlassian.net/browse/DOC-1013
- Update useEffect to try and fix the wrong calculation of the document width in staging.
=> Update useEffect for getting the image width

src/components/ImagePreview.tsx
https://hackney.atlassian.net/browse/DOC-1013
- Changed the way the width of the image is accessed to fix the issue in staging where the height is incorrectly calculated.
=> Change the way the width of the images is accessed

.circleci/config.yml, package-lock.json, package.json, src/components/EvidenceAwaitingSubmissionTile.test.tsx, src/helpers/formatters.test.ts, src/helpers/formatters.ts, src/pages/resident/[requestId]/confirmation.tsx, src/pages/resident/[requestId]/index.tsx, teams.json, test/setup.js
=> DOC -1204 - added copy to leashold & rtb team - added function to inject html 

src/components/DocumentTypeAndDescription.tsx, src/components/ResidentDocumentsTable.tsx, src/components/SelectDocumentType.test.tsx, src/components/SelectDocumentType.tsx
Fixed a bug with the document's title not showing on the resident's page.
=> Fix an issue with documents having no title on the resident page

src/components/SelectDocumentType.test.tsx, src/components/SelectDocumentType.tsx, src/services/staff-upload-form-model.ts
Add default select option for the staff upload form
=> Add default select option for the staff upload form

auth-groups.json
Add document products team to the production group
=> Add document products team to the production group

package-lock.json
Reverts LBHackney-IT/document-evidence-store-frontend#225
=> Revert "Bump jsdom from 16.4.0 to 16.7.0"

auth-groups.json, teams.json
https://hackney.atlassian.net/browse/DOC-1381
Adding the necessary configuration to onboard Parking Services to use DES
Config JSON files
=> DOC-1381: Onboarding Parking Services

src/components/ResidentDocumentsTable.tsx
Link to JIRA ticket:
https://hackney.atlassian.net/browse/DOC-1405
Show document description for documents uploaded by a member of staff
=> Show document description for documents uploaded by staff

src/gateways/internal-api.test.ts, src/gateways/internal-api.ts, src/pages/teams/[teamId]/dashboard/residents/create/index.tsx
Link to JIRA card:
https://hackney.atlassian.net/browse/DOC-1402
- Updated the call to the evidence-api to also pass the team name when creating a new resident
=> Update call to evidence-api to create a resident to pass team

src/components/ResidentSummaryTable.tsx, src/styles/ResidentSummaryTable.module.scss
https://user-images.githubusercontent.com/42063621/216623893-42bf36b6-b354-44c8-904f-d8e3080f655f.mov
=> DOC-1408 - Add Loading Spinner State On Resident Search Page

src/styles/ResidentSummaryTable.module.scss
https://user-images.githubusercontent.com/42063621/217233934-3e779c92-181a-401c-88c5-7f2174229466.mov
=> Fix Loading Spinner

cypress/integration/searches-automatically-from-deeplink.spec.ts, src/pages/teams/[teamId]/dashboard/deeplink/index.tsx
This page takes a query parameter in the URL, and automatically performs the search for the provided searchTerm.
=> DOC-1350 - Add Deeplink Search Page

auth-groups.json
This adds the configuration to allow Parking Services to access DES in Production.
=> DOC-1381: Authorise Parking Services to production

cypress/integration/searches-automatically-from-deeplink.spec.ts, src/components/ConfirmationDialog.test.tsx, src/components/ConfirmationDialog.tsx, src/components/LinkResidentSummaryTable.test.tsx, src/components/LinkResidentSummaryTable.tsx, src/gateways/internal-api.test.ts, src/gateways/internal-api.ts, src/pages/teams/[teamId]/dashboard/deeplink/index.tsx
https://hackney.atlassian.net/browse/DOC-1352
- Added the ability to link a Housing Register resident with a DES resident
- Added a confirmation dialog to confirm the link
- Added unit and integration tests
=> Add ability to link housing register residents with DES residents

cypress/fixtures/residents/merge-and-link.json, cypress/integration/create-resident-from-deeplink.spec.ts, cypress/integration/searches-automatically-from-deeplink.spec.ts, src/components/ConfirmationDialog.test.tsx, src/components/ConfirmationDialog.tsx, src/components/LinkResidentSummaryTable.test.tsx, src/components/LinkResidentSummaryTable.tsx, src/gateways/internal-api.test.ts, src/gateways/internal-api.ts, test/mocks/behaviours.json, test/mocks/fixtures/residents-requests.js
https://hackney.atlassian.net/browse/DOC-1348
Added the ability to merge and link residents.
- Added gateway function to make the relevant call to the evidence-api
- Added a new component to confirm merging
- Updated mock server with the new merge endpoint
- Added unit and cypress tests
=> Add feature to merge and link residents

serverless.yml
Added the token in serverless for the edit resident endpoint.
Important: At the time of this PR the edit resident endpoint is not being used yet.
=> Add tokens for the edit resident endpoint

package-lock.json, package.json
https://hackney.atlassian.net/browse/TS-2009?atlOrigin=eyJpIjoiNTQ1ODZlYjRjNTA1NGZkNjk1YmIyNjc5MGQxZDYxZTciLCJwIjoiaiJ9
**What:** Patches a [critical vulnerability](https://nextjs.org/blog/cve-2025-29927) on Next.
=> Patches next vunerability
