- cypress/fixtures/evidence-request-response.json
- cypress/integration/create-evidence-request.spec.ts
- cypress/integration/view-evidence-requests.spec.ts
- src/boundary/response-mapper.test.ts
- src/boundary/response-mapper.ts
- src/components/Checkbox.tsx
- src/components/EvidenceRequestTable.tsx
- src/components/NewRequestForm.tsx
- src/domain/evidence-request.ts
- src/domain/resident.ts
- src/gateways/internal-api.test.ts
- src/gateways/internal-api.ts
- src/pages/_app.test.tsx
- src/pages/_app.tsx
- src/pages/requests/index.tsx
- src/pages/requests/new.tsx
- types/page-component.d.ts
- Updates entity request models to have `documentTypes` as an array, to match the API response
- Updates the New Request form model to match Evidence Request, and hooks it up with the gateway
> Fix API integration for creating evidence requests

- cypress/integration/authentication.ts
- cypress/integration/create-evidence-request.spec.ts
- cypress/integration/view-evidence-requests.spec.ts
- package-lock.json
- src/components/DashboardLayout.tsx
- src/pages/dashboard/index.tsx
- src/pages/dashboard/requests/index.tsx
- src/pages/dashboard/requests/new.tsx
- src/pages/login.tsx
- move staff-facing routes under /dashboard, so that residents don't accidentally get a log in page any more if they visit the root url, and so we can properly build the staff-facing /resident routes.
- update cypress tests
> Reorganise routes

- cypress/integration/upload-a-document.spec.ts
According to the docs, [Cypress specs should be able to run independently of each other](https://docs.cypress.io/guides/references/best-practices.html#Having-tests-rely-on-the-state-of-previous-tests). 
This is probably because tests do not run in the same order each time, which explains why the specs could only sometimes not find the input (it had not loaded yet).
> Fix flaky Cypress spec

- src/components/EvidenceRequestTable.tsx
- src/components/ResidentTable.tsx
- src/pages/dashboard/index.tsx
- src/styles/globals.scss
- refactor resident search table to no longer use lbh-frontend-react's table component
- same for evidence request table
- make the resident search page actually use the right table
> Better tables

- src/gateways/evidence-api.test.ts
- src/gateways/evidence-api.ts
To ensure our env vars are consistent
> /api/v1 path in application, not in env var

- cypress/integration/authentication.spec.ts
- cypress/integration/create-evidence-request.spec.ts
- cypress/integration/search-for-resident.spec.ts
- cypress/integration/team-pages-authentication.spec.ts
- cypress/integration/view-and-manage-evidence.spec.ts
- cypress/integration/view-evidence-requests.spec.ts
- src/components/DashboardLayout.tsx
- src/components/EvidenceTile.test.tsx
- src/components/EvidenceTile.tsx
- src/components/ResidentSummaryTable.tsx
- src/components/ResidentTable.tsx
- src/components/TeamsLayout.tsx
- src/pages/teams/[teamId]/dashboard/index.tsx
- src/pages/teams/[teamId]/dashboard/requests/index.tsx
- src/pages/teams/[teamId]/dashboard/requests/new.tsx
- src/pages/teams/[teamId]/dashboard/residents/[residentId]/document/[documentId].tsx
- src/pages/teams/[teamId]/dashboard/residents/[residentId]/index.tsx
- src/pages/teams/index.tsx
- src/services/team-helper-helper.test.ts
- src/services/team-helper.test.ts
- src/services/team-helper.ts
- Paths are now `/teams/[teamId]/dashboard`
- `/requests`
- `/residents`
- Validate the user has access to the team for the `teamId` in the path `/teams/:teamId/…`
- Perform this during `getServerSideProps` as it's here we can route to a different page if the user should not be able to access the team page
> DES-141: nest residents and evidence pages under /teams

- cypress/fixtures/evidence_requests/id.json
- cypress/fixtures/evidence_requests/index.json
- src/boundary/response-mapper.test.ts
- src/components/ConfirmRequestDialog.test.tsx
- src/components/ConfirmRequestDialog.tsx
- src/components/NewRequestForm.test.tsx
- src/components/NewRequestForm.tsx
- src/components/SelectOption.tsx
- src/domain/evidence-request.ts
- src/gateways/evidence-api.test.ts
- src/gateways/evidence-api.ts
- src/gateways/internal-api.ts
- src/pages/teams/[teamId]/dashboard/index.tsx
- src/pages/teams/[teamId]/dashboard/requests/index.tsx
- src/pages/teams/[teamId]/dashboard/requests/new.tsx
- In new evidence request form provide a drop down list of reasons for the selected team
- Populate dropdown with reasons from JSON
- Pass Reason to EvidenceAPI
- Replace instances of `serviceRequestedBy: 'Housing benefit'` with `serviceRequestedBy: {teamName}`
> DES-159: provide a drop down list of reasons in new evidence request form

- cypress/integration/upload-a-document.spec.ts
- src/components/UploaderForm.test.tsx
- src/components/UploaderForm.tsx
- src/components/UploaderPanel.tsx
- src/gateways/evidence-api.test.ts
- src/gateways/evidence-api.ts
- src/gateways/internal-api.test.ts
- src/gateways/internal-api.ts
- src/pages/resident/[requestId]/confirmation.tsx
- src/pages/resident/[requestId]/upload.tsx
- src/services/__mocks__/upload-form-model.ts
- src/services/request-authorizer.ts
- src/services/upload-form-model.test.ts
- src/services/upload-form-model.ts
https://hackney.atlassian.net/browse/DES-175
- Call `EvidenceApiGateway.createDocumentSubmission` for each file that the resident provides
- Move calling `createDocumentSubmission` from `upload` to `upload-form-model`
- This meant moving `createDocumentSubmission` from `evidence-api` to `internal-api`
> DES-175: Call EvidenceApiGateway.createDocumentSubmission for each file that the resident provides

- src/boundary/response-mapper.test.ts
- src/boundary/response-mapper.ts
- src/helpers/formatters.test.ts
- src/helpers/formatters.ts
- src/helpers/register-domain.ts
- src/pages/teams/[teamId]/dashboard/residents/[residentId]/index.tsx
https://hackney.atlassian.net/browse/DES-170
- Display dates in the format _14:15 5 Jun 2020 (2 days ago)_
- Ensure Luxon `DateTime` are always created as UTC because they are stored in the database in this timezone (see https://hackney.atlassian.net/browse/DES-204)
- This means whenever `toLocal()` is called then they are adjusted into the user's timezone
> DES-170: show timestamp associated with each document submission

- cypress/fixtures/document_submissions/get-approved.json
- cypress/integration/view-and-manage-evidence.spec.ts
- test/mocks/behaviours.json
- test/mocks/fixtures/document-submissions.js
Added a new behaviour to the mock server for the approved document
Added a cypress test for the copy to clipboard button (functionality can't be tested in the dev environment as it only works in https)
> Add mock server behaviour for approved document and cypress test

- cypress/integration/view-and-manage-evidence.spec.ts
- src/gateways/evidence-api.test.ts
- src/gateways/evidence-api.ts
- src/gateways/internal-api.test.ts
- src/gateways/internal-api.ts
- src/helpers/Constants.ts
- src/pages/api/evidence/[...path].ts
- src/pages/resident/[requestId]/confirmation.tsx
- src/pages/resident/[requestId]/index.tsx
- src/pages/resident/[requestId]/upload.tsx
- src/pages/teams/[teamId]/dashboard/index.tsx
- src/pages/teams/[teamId]/dashboard/requests/index.tsx
- src/pages/teams/[teamId]/dashboard/requests/new.tsx
- src/pages/teams/[teamId]/dashboard/residents/[residentId]/document/[documentSubmissionId].tsx
- src/pages/teams/[teamId]/dashboard/residents/[residentId]/index.tsx
- src/services/upload-form-model.test.ts
- src/services/upload-form-model.ts
https://hackney.atlassian.net/browse/DES-276
* `EvidenceApiGateway`
*  Decided to pass `userEmail` as the first parameter in functions because some functions have optional arguments which meant `userEmail` couldn't always be passed as the final param. I thought it was better to have consistency so pass it as the first param
* `InternalApiGateway`
* Retrieve `req. headers` from the Axios request in `[...path]` and pass them on to `EvidenceApiGateway.request`. This extracts `useremail` from the headers provided and attaches it along with `Authorization` when sending requests to the evidence-api
> DES-276: Update API calls from Frontend to include user email

- serverless.yml
- src/gateways/documents-api.ts
- src/gateways/evidence-api.ts
- src/gateways/internal-api.ts
We saw the following error in the `document-evidence-frontend` log:
```
ERROR	Error: self signed certificate in certificate chain
at TLSSocket.onConnectSecure (_tls_wrap.js:1502:34)
at TLSSocket.emit (events.js:314:20)
at TLSSocket._finishInit (_tls_wrap.js:937:8)
at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:711:12) {
code: 'SELF_SIGNED_CERT_IN_CHAIN',
```
To (hopefully) fix it we followed [this guide](https://stackoverflow.com/questions/51363855/how-to-configure-axios-to-use-ssl-certificate) to add additional configuration to Axious
> DES-253: provide palo altos SSL certificate to axios

- .env.sample
- serverless.yml
- src/gateways/evidence-api.ts
- src/services/request-authorizer.ts
`NODE_ENV` is either `development` or `production` so we cannot use it to decide behaviour if we're in `staging`. See comment https://github.com/vercel/next.js/issues/3605#issuecomment-370255754
> DES-253: introduce APP_ENV

- next.config.js
- src/gateways/evidence-api.ts
- Create `PALO_ALTOS_SSL_CERTIFICATE` env variable instead of reading the certificate from disk every time we instantiate `EvidenceApiGateway`
> DES-253: create PALO_ALTOS_SSL_CERTIFICATE env variable

- next.config.js
- src/gateways/evidence-api.ts
Still facing the error after #112 and #113:
```
ERROR	Error: self signed certificate in certificate chain
at TLSSocket.onConnectSecure (_tls_wrap.js:1502:34)
at TLSSocket.emit (events.js:314:20)
at TLSSocket._finishInit (_tls_wrap.js:937:8)
at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:711:12) {
code: 'SELF_SIGNED_CERT_IN_CHAIN
```
Think we will need to additional parsing of `fs.readFileSync('/opt/palo-alto-ssl-certificate.crt'` into `PALO_ALTOS_SSL_CERTIFICATE` variable. Reverting this change for now because it feels like we're trying to prematurely optimise, and reading the certificate from disk every time we instantiate `EvidenceApiGateway` may be fine for now
> DES-253: revert PALO_ALTOS_SSL_CERTIFICATE env variable

- cypress/integration/upload-a-document.spec.ts
- src/gateways/documents-api.ts
- teams.json
Remove housing team from the list of teams as it's not intended for anyone to use it.
> Remove housing team from the list of teams

- cypress/integration/view-and-manage-evidence.spec.ts
- src/components/EvidenceTile.test.tsx
- src/components/EvidenceTile.tsx
- src/pages/teams/[teamId]/dashboard/residents/[residentId]/document/[documentSubmissionId].tsx
Refactor AcceptDialog and RejectDialog to not be on a different link. Previously, when opening the accept/reject dialog we had `?action=accept` and `?action=reject` attached to the link which meant that anyone could add that to the link of the document details page and get back that dialog box after accepting/rejecting the document which is unwanted behaviour.
> Refactor AcceptDialog and RejectDialog to not be on a different link

- src/components/EvidenceRequestTable.tsx
- src/components/ResidentTable.tsx
- src/helpers/sorters.test.ts
- src/helpers/sorters.ts
- Sorted evidence requests from newest to oldest on the requests and residents pages
> Add sorting for evidence requests from newest to oldest

- src/components/AcceptDialog.test.tsx
- src/components/AcceptDialog.tsx
- src/components/EvidenceRequestTable.tsx
- src/components/ResidentTable.tsx
- src/gateways/internal-api.ts
- src/pages/teams/[teamId]/dashboard/residents/[residentId]/document/[documentSubmissionId].tsx
- Displayed the error message coming from the backend APIs
- Refactored document details page and moved the approve functionality on to the `AcceptDialog` component
- Commented out table headers that were visually hidden to remove the unnecessary spaces and improve the UI
> Allow only future date when approving a document and comment out headers

- src/components/Field.tsx
https://hackney.atlassian.net/browse/DES-341
WAVE flags the 3 input boxes with:
> An aria-labelledby or aria-describedby reference exists, but the target for the reference does not exist.
Because the HTML is
`<input name="resident.name" id="resident.name" aria-describedby="false" class="govuk-input lbh-input null" value="">`
Setting the value to `null` instead of `false` if a hint isn't provided fixes this
> DES-341: Fix broken ARIA references

- src/components/NewRequestForm.tsx
Change new request form document types from radio buttons to checkboxes to be able to select multiple types for a single evidence request
> Change new request form document types from radio buttons to checkboxes

- cypress/integration/view-and-manage-evidence.spec.ts
- src/components/AcceptDialog.tsx
- src/services/request-authorizer.ts
**Ticket**
https://hackney.atlassian.net/browse/DOC-537
**Problem**
In this issue, a user could approve their own uploaded documents by intercepting the request and changing the body to "status: approved". This is because the document_submission url was whitelisted from Google Auth, meaning that an unauthenticated user could access that URL. You could practice this locally by removing the auth token before you hit "Submit" when approving a document.
**Solution**
We removed the URL from the whitelist and configured the error handling so that the user is redirected to the login page when they are missing their token.
**Tests**
We have also added in an acceptance (Cypress) test to check that if a user submits a validity date that is in the past, then the correct error shows up.
The tests to …
> Remove whitelisted url and amend error handling

- src/components/UploaderPanel.tsx
https://hackney.atlassian.net/browse/DOC-542
From the security test, we identified that we needed to whitelist file extensions/mime types when the API receives a request. This list can be quite long, so we've refactored it to make it easier for future developers to remove/add mime types.
A new file with all accepted mime types.
> Add full list of accepted mime types

- cypress/integration/upload-a-document.spec.ts
- src/components/FileFormatsDetails.tsx
- src/pages/resident/[requestId]/upload.tsx
Link to Jira card: 
https://hackney.atlassian.net/browse/DOC-545
- Added a new component FileFormatsDetails
- Added the component on the upload page to show our users the file extensions that we currently accept in the system
- Updated the cypress tests to check for the new component on the screen
> Create file format details component and add it on the upload page

- README.md
I've added new instructions for the frontend. It specifies that the other two repos (evidence-api and documents-api) must be running before the frontend can successfully run locally.
> Update README to include new start up, testing instructions and MIME types

- src/gateways/documents-api.test.ts
- src/gateways/documents-api.ts
- src/pages/teams/[teamId]/dashboard/residents/[residentId]/document/[documentSubmissionId].tsx
- test/mocks/behaviours.json
- test/mocks/fixtures/get-download-url.js
The link to JIRA ticket is here: https://hackney.atlassian.net/browse/DOC-614
The purpose of this feature is to implement the new download path from S3 on the frontend. Instead of retrieving the document as a base64 encoding, the FE now calls documents api that returns a presigned url from S3.
In this PR, we've added a new gateway to get the download link from documents api and renders the document using this url on the page.
> Change download document page to use presigned url instead of base64

- auth-groups.json
- teams.json
Linked to this ticket: https://hackney.atlassian.net/browse/DOC-564
In this PR, we just needed to add the Google group that Lewis has created to the frontend config. I've tested this locally and I can access the group (once I cleared my cookies and logged back in again).
> Add Leasehold and Right To Buy group to staging

- src/gateways/internal-api.test.ts
- src/gateways/internal-api.ts
- src/services/request-authorizer.ts
- src/services/upload-form-model.test.ts
- src/services/upload-form-model.ts
Link to Jira card: https://hackney.atlassian.net/browse/DOC-870
- Added a call to evidence-api so that after each successful upload of documents the resident receives a confirmation by email/SMS
- Added tests
> Add call to evidence-api to send a confirmation notification to resident

- src/gateways/internal-api.test.ts
- src/gateways/internal-api.ts
- src/services/upload-form-model.test.ts
- src/services/upload-form-model.ts
https://hackney.atlassian.net/browse/DOC-906
Following on from the [story](https://hackney.atlassian.net/browse/DOC-871) to reduce the amount of emails sent to the Hackney staff member, we decided to send a request for the email to be sent when the resident has uploaded the documents. This feature uses an endpoint created in a previous feature that sends a confirmation code to the resident. I've amended this in Evidence API so that it also sends an email to the staff member.
This PR changes the name of this method on the FE to accurately reflect the changes in the API.
Approve the Evidence API code.
> Rename method as endpoint now has added functionality

- cypress/integration/upload-a-document.spec.ts
- cypress/integration/view-and-manage-evidence.spec.ts
- src/components/PhotoInformation.tsx
- src/pages/resident/[requestId]/index.tsx
- src/pages/resident/[requestId]/upload.tsx
Refers to this ticket: https://hackney.atlassian.net/browse/DOC-851
In this commit, I've updated the landing page and moved the photography guidance text that was there onto the upload page.
On the upload page, I've added guidance for alternate options for uploading documents. I also removed the function to pluralise the 'Document' in the title, because even if one document type was requested, a resident can still upload multiple documents (plus it's consistent with all the other refs to documents on the page).
> Guidance for more options on how to upload documents for residents

- auth-groups.json
https://hackney.atlassian.net/browse/DOC-746
Paul Canning has asked for the Leasehold and Right to Buy team to be added to the production (live) environment.
In auth-groups.json, I have added the Google Group 'Leasehold and Right to Buy' to production.
Tell Paul that he should have access to prod now.
> Add Leasehold and Right to Buy to production environment

- .env.sample
This PR updates the frontend's .env.sample environment variables with the latest API urls, after their Docker files have been reconfigured. More info about that feature can be found here: https://hackney.atlassian.net/browse/DOC-876
Developers will need to make sure that their .env file is up-to-date with these envars in order to do local development with the API containers.
NOTE: I've found that the .env.sample are coupled to Cypress in some way in order to run the tests locally and in the pipeline -- it's not clear how for now, but I've updated the .env.sample to include both set ups. We can have a look into this further when we make a container for the frontend.
> Update .env.sample with latest envars for Docker

- cypress/integration/view-and-manage-evidence.spec.ts
- src/components/AcceptDialog.test.tsx
- src/components/AcceptDialog.tsx
- src/components/DateFields.tsx
In this PR, I've added in some validation to the Yup schema to check if the date that a user has inputted is valid.
So now, there are a few scenarios that are now covered:
1. A user does not input a date. The validation lets this happen and the following request is sent to the API
2. A user inputs a possible 
date. The validation lets this happen and the following request is sent to the API
3. A user inputs a fake date (e.g. 32nd of Dec). The form throws an error.
4. If a user enters a date, then removes it, the form will reset the validation and the following request will be sent to the API
Any dates that are entered in the past is handled by the API (business logic, rather than view logic, would sit in there). 
In the case of services integrated with our API, we parse the date in …
> Fix error for non-existent date when accepting a document

- src/components/UploaderForm.tsx
This is to prevent the submit button being re-enabled before the router pushes the user to the next page onSuccess.
> Move state change to catch block to prevent button re-enabling

- src/components/UploaderPanel.tsx
Allow MIME-type image/heif files to be accepted so the officer can view documents submitted with that type.
See the ticket for more details
[https://hackney.atlassian.net/browse/DOC-1101](url)
> 'Add .heif to accepted mime types'

- src/components/PageWarning.tsx
- src/components/UploaderForm.test.tsx
- src/components/UploaderForm.tsx
We will displaying a warning to discourage residents closing or reloading the browser window while their documents are uploading.
This is to minimise those instances where records are created but documents never reach S3.
> DOC-1202: Displaying warning while documents are uploading

- cypress/integration/upload-a-document.spec.ts
- src/components/EvidenceAwaitingSubmissionTile.test.tsx
- src/pages/resident/[requestId]/confirmation.tsx
This PR aims to change the wording in the confirmation page so the residents are aware that there are still checks to be carried out on uploaded documents.
"We've received your documents" becomes "We’re checking your documents"
"We’ve sent your evidence to the service that requested it. They will be in touch about the next steps." becomes "We’re checking your evidence. It’ll be sent to the service that requested it if it meets our requirements."
There is also a small change to a preexisting test that kept failing (using the toRelativeCalendar function to compare date to return a consistent result, in order for it to be compared to the test)
> DOC 1214 - Reword confirmation messages to residents following upload

- src/components/ImagePreview.tsx
- src/components/RotateDocument.tsx
https://hackney.atlassian.net/browse/DOC-1013
- Added aspect ratio to display the image correctly when turned at 90 degree and 270 degrees.
- Removed the calculation of image width as we don't need the initial width, but the one after the image is resized.
> Add aspect ratio and remove imageWidth calculation

- cypress/fixtures/document_submissions/get-many-response-object.json
- src/gateways/evidence-api.test.ts
- src/gateways/evidence-api.ts
- test/mocks/fixtures/document-submissions.js
- types/api.d.ts
Added `DocumentSubmissionResponseObject` to match the response received from evidence-api when getting document submissions for a resident.
> Add DocumentSubmissionResponseObject to match the response from evidence-api

- cypress/integration/view-and-manage-evidence.spec.ts
- src/boundary/response-mapper.ts
- src/components/EvidenceTile.test.tsx
- src/components/EvidenceTile.tsx
- src/components/ResidentDocumentsTable.tsx
- src/components/StaffUploaderForm.tsx
- src/domain/document.ts
- types/api.d.ts
Added document description to the EvidenceTile so it's easier for our users to identify what that document is before clicking on it from the resident's page.
> Add document description to the EvidenceTile

- src/components/ResidentDocumentsTable.tsx
In the [previous iteration ](https://github.com/LBHackney-IT/document-evidence-store-frontend/pull/283), when there were no evidence requests in the Awaiting Submission tab, the "There are no documents to review" label was not displayed correctly. 
This PR remediates that.
> DOC-1359: Proper visualisation when there's no awaiting submission ERs

- .circleci/config.yml
- src/components/CreateResidentForm.tsx
This change does not set the isLoading state to false after the resident is created - ensuring that the loading spinner remains active until the user is redirected to the newly created resident.
> do not set isLoading false

- src/pages/teams/[teamId]/dashboard/requests/new/[step].tsx
Current functionality shows internal AWS server name in URL
> Use JS to generate server name as lambda doesn't know about cloudfront
